### ISSUE TITLE
Use headers to transport api_key?

### ISSUE THREAD

**Issue by cehbrecht** [ESGF/esgf-compute-api#47]
Currently the `api_key` is added as a parameter to the request URL. I would prefer to have it in the HTTP headers. Technically both work ... for testing the URL parameter is also more convenient. But I suppose the security people don't like to see api_keys in log files.

See also notebook example:
https://github.com/bird-house/OWSLib-esgfwps/blob/master/examples/notebooks/pelican-wps-demo.ipynb

**Comment by jasonb5** [comment]
We were planning for this on server-side ESGF/esgf-compute-wps#184 as well.

I was planning on removing the GET parameter all together since a header would work with both GET and POST requests. For the implementation I was planning on allowing the user to specifiy the name of the token since each institution may have a unique name, unless there's a specific name we should be using, then I can hardcode it.

**Comment by jasonb5** [comment]
This has been added https://github.com/ESGF/esgf-compute-api/blob/0119d1a5adce6de6ddad34366adc5f1ff98ed5b0/cwt/wps_client.py#L70-L75
